### ISSUE TITLE
Save Name does not accept capitals

### ISSUE THREAD

**Issue by nukebloodaxe** [nukebloodaxe/ironseed_fpc#10]
It's an odd bug I spotted today, when selecting the save position and changing the name, the save slot name cannot be created with capital letters.  It produces numbers in their place instead, suggesting this is an ASCII lookup bug.

**Comment by mnalis** [comment]
It is probably two things:

- pressing `shift`/`alt`/`ctrl` on their own used to generate numbers, due to (now solved) bug https://github.com/mnalis/ironseed_fpc/issues/2 so that problem is gone at least!

- but using MixedCase is no go currently. FPC version of game in `c_utils.c` reads the keyboard via `SDL_KEYDOWN` events (instead of original CRT readkey() in DOS), and thus does not support your OS keyboard mappings, including generating ASCII on `shift`+`key` or `Caps Lock` or anything like that, so no MixedCase is possible. While current version could theoretically support generating different ASCII with and without by creating special key mapping for every letter on keyboard, it would be not only very long list, but would become nightmare when you consider not only UPPERCASE/lowercase letters, but all special charactes on shift+nonletter (numbers, ",", ".", "<", ">", "`", "-", "+"....) and all the different keyboard layouts in various countries... We would need completely different handler than `SDL_KEYDOWN` which uses `xkbmap`/`xev` mappings or something similar. Given that this is only place in game where MixedCase could even be used, I don't think it is such a big deal.

**Comment by nukebloodaxe** [comment]
Hmmm, thinking of cellphones, this would work with a toggle button.  However, you are right, it's not really big or necessary, just a point of interest.

**Comment by mnalis** [comment]
After taking a deeper look at [SDLKey](http://sdl.beuc.net/sdl.wiki/SDLKey) docs:  

> at last, never ever ever write your own custom ASCII conversion table. If you do that, you'll get angry non US users that will pester you to fix the keyboard handling for them, one for each keyboard layout existing in the world. If you want to know the symbol entered by the user, the SDL_KeyboardEvent event is the good place to do it.  

While the `keysym` we currently use does not take shift into consideration, [SDL_KeyboardEvent](http://sdl.beuc.net/sdl.wiki/SDL_KeyboardEvent) comment says that [SDL_keysym](http://sdl.beuc.net/sdl.wiki/SDL_keysym) `unicode` member should be taking `SHIFT` into consideration if [SDL_EnableUNICODE](http://sdl.beuc.net/sdl.wiki/SDL_EnableUNICODE) is enabled. Should probably enable [SDL_EnableKeyRepeat](http://sdl.beuc.net/sdl.wiki/SDL_EnableKeyRepeat) while we're there if we try that, to enable easier scrolling in those long lists...

**Comment by mnalis** [comment]
Should be solved now - savegame allows entering of lowercase/uppercase
